### ISSUE TITLE
Clicking an image selects it, but does not add highlighting

### ISSUE THREAD

**Issue by eXist73** [rvera/image-picker#100]
I'm using bootstrap and including the library as so:
```
    <link href="/css/image-picker.css" rel="stylesheet">
    <script src="/js/image-picker.min.js"></script>
```

Everything initializes correct, but when I try to select an image via **clicking** on it, the highlighting does not appear.  If I use the option: **hide_select: false** and change the image via the select drop down, the highlighting works.

**Update**
This seems to only be an issue with the **minified** version, the non-minified version works as expected.

**Comment by rvera** [comment]
Seems like it was an issue with the minified version, will be fixed on the new release. Thanks for reporting this.
