### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by Humni** [rvera/image-picker#104]
There are 3 pull requests without any comment from the @rvera or any other user with write access (is there any?), with one request dating back to January 2017. If this is no longer maintained I would be happy to pick it up, at the very least manage pull requests and issues with write access

**Comment by jeffbocala** [comment]
Started [Box Image Picker](https://github.com/jeffbocala/box-image-picker) since I needed the library but saw that this one was inactive. Feel free to add feature requests or report bugs.

**Comment by Humni** [comment]
@jeffbocala Its back alive! I've been given write access and I have a release I'm preparing for in a few weeks

**Comment by jbcl-io** [comment]
@Humni – Awesome! Will happily be contributing to this.
