### ISSUE TITLE
Transitions not working

### ISSUE THREAD

**Issue by thiagobrez** [rvera/image-picker#106]
I followed the steps of implementation but when changing from one image to another there is no transition applied, like in the [presentation site](http://rvera.github.io/image-picker/). I guess, does the transition CSS even come in the package? Looked through the files and just couldn't find it. I'm sure both the CSS and JS are being called because I've put a console log in the JS and changed the selected background color for the CSS. Double-checked the import paths, tried importing from cloudfare, tried multiple jQuery versions and the select structure code I copied from the examples. No problem if I gotta do it manually, but I was wondering that if it is already included it'd be better to use it as is. Thanks in advance.

**Comment by rvera** [comment]
They don't come, with the package. It's up to the implementation, in the example site it's bootstrap doing all the work. It's basically doing `transition: all 0.2s ease-in-out;` on the `.thumbnail` class.
