### ISSUE TITLE
Beginner help! 

### ISSUE THREAD

**Issue by dianamwabala** [rvera/image-picker#113]
Hello, Thank you for this! I am a total beginner in programming/JS, so I hope you don't mind if I ask stupid questions. 

Uhmm.. I installed this but I am not sure if I did it right... Now I am trying to add my photos instead of your cats, and my photos don't show (or yours for the matter).. Was there something else I had to besides installing the JS  (I added it in my theme content, functions.php, and then added the HTML from your examples where I want it to be)... ? 

You say also things "just call imagepicker on the target elements." -- how do I do that? 

Hope you can clear my mind and illuminate me. Thank you! :)

**Comment by dianamwabala** [comment]
Alright - I just added $("select").imagepicker() in the JS and I can now see the photos, but I cannot select them... Help..?

**Comment by Humni** [comment]
Hello, this is the area where users report issues with the library, rather than questions on how to get started. I would like to point you towards https://stackoverflow.com/ for questions that you have!
