### ISSUE TITLE
Multiple functions on select.

### ISSUE THREAD

**Issue by Powers-RC** [rvera/image-picker#116]
I am wondering if anyone has or knows how to call on several functions when an image is selected? I am considering just chaining the functions together by calling them inside the `select: function()` but I am against doing this. Also wondering if anyone has tried chaining multiple `.imagepicker()` functions together and how that resulted? I am getting ready to try all this so I will update this if I find a solution. Just wondering if someone has accomplished this already.

**Comment by Powers-RC** [comment]
I am reopening this issue because I am having trouble running multiple functions on select still. It seems that every time I select an option only one of the functions runs. Any suggestions on how to accomplish this?

**Comment by rvera** [comment]
Hi @Powers-RC, the interface only defines one callback, if you need to call multiple functions you would need to call them all inside that one callback. ie,

```
select: function() {
  methodA();
  methodB();
}
```

If this list is dynamic you would need to store them somewhere (like a map or array) and the iterate over this list to call them one by one.

**Comment by Powers-RC** [comment]
Thank you, this is what I needed to know.

**Comment by Powers-RC** [comment]
So I am trying to loop through my functions but it still seems to be only executing the last one. I think it is because I am calling 
`$(select).imagepicker({
    selected function(){}
});`
in all of them. Could this be the problem?

Below is a snippet of my function that calls my other functions and an example of them. 
`function onClick(){
    $(document).ready(function(){
        $("select").imagepicker({
            selected:function(){
                var func_lst = [getValue(), removeOptions(), placeImages(feature_lst, min)]
                for(i=0; i < func_lst.length-1; i++){
                    func_lst[i];
                };
            }
        });
    });
}`


`function removeOptions(select){
    $(document).ready(function(){
        $("select").imagepicker({
            selected:function(option){
                document.getElementsByClassName('picker')[0].options.length = 0
            }
        });
    });
}`
