### ISSUE TITLE
destroy() is undefined!

### ISSUE THREAD

**Issue by seemugia1** [rvera/image-picker#118]
I tried:
$("#myselect").data('picker').destroy()
but property destroy is undefined

**Comment by rvera** [comment]
Thanks, will take a look

**Comment by Humni** [comment]
I believe this is working, I've tested this on the demo with no major issues. The only complication that I came into was when there were multiple selectors on the page, you can't destroy them all at once, you have to do it one by one. Am closing this issue for now, but if you have any other information or context to provide the bug report feel free to comment it.
