### ISSUE TITLE
safari support

### ISSUE THREAD

**Issue by OliverLeitner** [rvera/image-picker#127]
hi,

first of all, thanks for the nice plugin, it does seem to work mostly except for one browser "situation".

i am testing with safari on windows (most current build available for windows is safari 5...) and i get the following error:

`ReferenceError: Can't find variable: WeakMap`

does anyone else here have an issue with safari, maybe there is a workaround for that?

**Comment by Guite** [comment]
Sure this error is caused by the image picker? Because the source code does not contain any reference to `WeakMap` at all.

**Comment by Humni** [comment]
Safari for With does is not supported by Apple, and was lost support some years ago. Unless you find this error with Safari on Mac, I don't think it's an issue

**Comment by OliverLeitner** [comment]
ok, i think this is specific to the windows version of safari, which apparently is 10 years old.

obviously apple doesnt play nice with others...
