### ISSUE TITLE
Modal or Pop-Up Mode

### ISSUE THREAD

**Issue by jneilliii** [rvera/image-picker#129]
Is it possible to use this plugin as a modal pop-up for image selection?  All the demos appear to be inline and outside of that the plugin works perfectly for my use case.  I'd like to be able to display the select list, and on click show the modal image picker window allowing for multi-select, etc.

**Comment by Humni** [comment]
You should be able to embed the image picker inside a modal, based on a button click which opens the modal, if you embed the image picker inside a modal and initialize it after the modal has been loaded then it should all work as expected. I'll close this for now but if you run into trouble I don't mind re-opening the issue to get it working for this use case.
