### ISSUE TITLE
Looking for someone to take over

### ISSUE THREAD

**Issue by rvera** [rvera/image-picker#135]
I think it's time to accept life got too in the way and I can't maintain this anymore.I'm looking for someone to take over, looking at the history the following users have been good contributors:

@Humni 
@rdennis 
@floo51 
@kkalpakloglou
@jbatchelor

Please respond if any of you is interested in taking over

**Comment by Humni** [comment]
I'd be interested in taking over, have offered in the past too and think that this still has some great potential

**Comment by Humni** [comment]
@rvera any updates?

**Comment by Humni** [comment]
@rvera still waiting... sorry to be impatient but I'm really keen to get a v1.0.0 out for this with some major improvements!

**Comment by Humni** [comment]
All done! Happy to take more contributions from everyone 💃
