### ISSUE TITLE
how to change default first selected option?

### ISSUE THREAD

**Issue by CodeCurosity** [rvera/image-picker#136]
First image is selected by default, how can i change that, i don't want any image to be selected initially?

**Comment by array81** [comment]
Quote. On start the plugin seems to ignore the select value, always the first item is selected.

**Comment by supairish** [comment]
@CodeCurosity Have the first option in your select be blank

**Comment by CodeCurosity** [comment]
@supairish very strange and it shouldn't be like this, it should pick up the selected attributed from the option but anyways adding this as first option works.<option value=""></option>

**Comment by supairish** [comment]
For future readers to play with

<p class="codepen" data-height="265" data-theme-id="0" data-default-tab="css,result" data-user="supairish" data-slug-hash="YoEYmX" style="height: 265px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;" data-pen-title="Image Picker">
  <span>See the Pen <a href="https://codepen.io/supairish/pen/YoEYmX/">
  Image Picker</a> by Chris Irish (<a href="https://codepen.io/supairish">@supairish</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
