### ISSUE TITLE
Option to change style of images that are not selected

### ISSUE THREAD

**Issue by CloudTheWolf** [rvera/image-picker#137]
Not sure if there is something already in place for this, but I'm looking for a way to change the style of the images that are not the selected one.

Eg All 3 Images start at 100% opacity. I select image 2 (The normal selected styles apply) and images 1 and 3 reduce opacity to 20%.

**Comment by Humni** [comment]
You should be able to use CSS for this. You will be able to ask this on StackOverflow as this is not specific to this library I believe (please comment if you believe otherwise)
