### ISSUE TITLE
You do `this.val()`, look at this jsfiddle, hope it helps

### ISSUE THREAD

**Issue by urpandey88** [rvera/image-picker#140]
Dear Sir,
Thanks for posting this an amazing post.

Kindly help me to remove the selected image id after unselecting image.

jQuery("select.image-picker").imagepicker({
        hide_select: true,
        selected: function (option) {
            values = this.val();       
          alert(values);
        },
         
    });

**Comment by Humni** [comment]
Questions like these are better suited for StackOverflow. If you encounter a bug, happy to help if you provide a JS Fiddle with the issue you've encountered.
