### ISSUE TITLE
How to unselect all selected with javascript?

### ISSUE THREAD

**Issue by viratsoft** [rvera/image-picker#143]
How to unselect all selected with java script?

Ex:
<script type="text/javascript">
$("select").data('picker').un-selecte-all();
</script>

**Comment by pinkopaio8** [comment]
Did you tried with a button and attribute "reset"?
This script after all is just a select box, I guess it should work?

**Comment by Humni** [comment]
You can deselect the options in the select box then use `$("select").data('picker').sync_picker_with_select();` to syncronize the image picker with the select box again. A future version will do this automatically for you
