### ISSUE TITLE
image-picker always selects first image

### ISSUE THREAD

**Issue by st-keller** [rvera/image-picker#25]
Hi
if i Initialize image-picker by calling `$("select").imagepicker()` the first image is always selected.

It would be very cool, if image-picker could keep the selection (third image in this example):

``` html
<select class="image-picker show-html">
  <option data-img-src="img/01.png" value="1">  Page 1  </option>
  <option data-img-src="img/02.png" value="2">  Page 2  </option>
  <option data-img-src="img/03.png" value="3" selected>  Page 3  </option>
</select>
```

How can I achieve this?

**Comment by sean-gilmore** [comment]
For anyone else stumbling upon this issue, you're probably missing the first empty option that should be included in you select, as per the documentation:

```
<select class="image-picker">
  <option value=""></option>
  <option data-img-src="http://placekitten.com/300/200" value="1">Cute Kitten 1</option>
  <option data-img-src="http://placekitten.com/150/200" value="2">Cute Kitten 2</option>
  <option data-img-src="http://placekitten.com/400/200" value="3">Cute Kitten 3</option>
</select>
```

The first `<option value=""></option>` is required to resolve this issue.
