### ISSUE TITLE
Clarification of the Changed functionality

### ISSUE THREAD

**Issue by sleyb** [rvera/image-picker#26]
Can someone clarify in the examples section of the usage of the changed value?

I would like to be able to click on one of the selected images and have that trigger an ajax request.

**Comment by gdvalderrama** [comment]
@sleyb You probably want to use 'clicked' or 'selected' then, rather than 'changed'.
The first to refer to changes at the option level, while 'changed' is at the picker level.

**Comment by rvera** [comment]
Thanks @gdvalderrama for answering this.
