### ISSUE TITLE
does not work when using with jquery mobile 1.4 and jquery 2.0

### ISSUE THREAD

**Issue by krisred** [rvera/image-picker#27]
the plugin initiates but nothing is displayed
<ul class="thumbnails image_picker_selector"></ul> is empty

**Comment by dereckmartin** [comment]
Yes, I can not get this to work either.

**Comment by rvera** [comment]
Hi @dereckmartin can you provide a link with an example?

**Comment by dereckmartin** [comment]
@rvera Please disregard.  It works.

**Comment by rvera** [comment]
What was wrong? This seems like a common concern.

**Comment by dereckmartin** [comment]
I had a typo.
