### ISSUE TITLE
Using Masonry with Image-picker

### ISSUE THREAD

**Issue by LymanZerge** [rvera/image-picker#28]
Can you please give an example of using Masonry with Image-picker ?
I tried putting the `select` in `<div id="container">` but it doesn't seem to work.
original question: http://stackoverflow.com/questions/22338582/use-fixed-image-size-in-jquery-image-picker-tool?noredirect=1#comment33990988_22338582

**Comment by rvera** [comment]
The demo page has an (old) example
```
    var container = jQuery("select.image-picker.masonry").next("ul.thumbnails");
    container.imagesLoaded(function(){
      container.masonry({
        itemSelector:   "li",
      });
    });
```

For more info I'd recommend checking out the official masonry docs.
