### ISSUE TITLE
Get selected image via jquery

### ISSUE THREAD

**Issue by ChristianGiupponi** [rvera/image-picker#31]
How can I get the selected image?

**Comment by easytraxbd** [comment]
I am getting error Uncaught TypeError: Cannot read property 'selected_values' of undefined

**Comment by IvanML19** [comment]
> I am getting error Uncaught TypeError: Cannot read property 'selected_values' of undefined

probably you are using an incorrect selector. the selector ' $("select") ' is generic. you should use your selector (by ID, class, etc...)

**Comment by Humni** [comment]
@IvanML19  how to do this is in the docs http://rvera.github.io/image-picker/
