### ISSUE TITLE
Dependency on version of jQuery

### ISSUE THREAD

**Issue by marsanyi** [rvera/image-picker#32]
Doesn't work with jQuery 1.4.2; does with jQuery 2.1.0.min; documentation update?

**Comment by garygreen** [comment]
+1. I've just been debugging a weird error for ages, turned out to be this plugin code reponsible:

```javascript
      thumbnail.click({
        option: this
      }, function(event) {
        return event.data.option.clicked();
      });
```

So strange, is this delegation? I changed it to the following, works fine. `.proxy` has been around since jQuery 1.4.

```javascript
      thumbnail.on('click', $.proxy(function() {
        return this.clicked();
      }, this));
```

**Comment by rvera** [comment]
@garygreen can you explain a little what issues were you seeing?

**Comment by garygreen** [comment]
@rvera honestly, I haven't got a clue what was happening but when it hit that bit of code it was executing some other js parts of my app, completely unrelated to image picker. I've never seen that syntax used before (passing object of options to the click event listener).

**Comment by rvera** [comment]
Will close this for now, since I can't pinpoint the error. Might be fixed on the newest version.
