### ISSUE TITLE
Get clicked image in clicked function?

### ISSUE THREAD

**Issue by eappell** [rvera/image-picker#35]
I'm trying to figure out how to get the actual image that was clicked (not the option) within the clicked callback.  I can see how to get the clicked option, but not the actual image, which I need because I want to run some code on each image as it is clicked...  Thanks!

**Comment by sridharraman** [comment]
Hi @eappell, I am trying to get the actual image object. Were you able to do it?

**Comment by eappell** [comment]
@sridharraman No, I was never able to get this to work for me.  I ended up using a Kendo UI gallery component for this particular functionality, and it worked well.  Still in use today.

**Comment by rvera** [comment]
@sridharraman once you access your select element with jquery eg `var select_element = $("#my-select-element")` you can simply do `select_element.data('picker').picker` and it will return the whole `ul` element for the picker, from there you can access all the images with regular jquery images.

**Comment by sridharraman** [comment]
@eappell, okay, I managed to do it by getting the selector option objects and getting the data attribute from each of option.

Sample:
```
$("select option:selected").each ->
  console.log($(this).data("img-src"))
```

**Comment by rvera** [comment]
@sridharraman you can also access the picker options programmatically

eg
```
var select_element = $("#my-select-element")
var picker = select_element.data('picker').picker
// Do a jquery to find all the selected elements
picker.picker.find("thumbnail.selected img")
// Or peek at the internal picker options and check which are selected
picker.picker_options[0].is_selected()
```

**Comment by eappell** [comment]
Awesome!  Glad this eventually got solved!

**Comment by nnsense** [comment]
I just wanted to say Thank you @rvera for the jfiddle posted  on 22 Apr 2014, I was struggling trying to achieve that, I think that example should be on project's main page!
