### ISSUE TITLE
Hide only the original selector?

### ISSUE THREAD

**Issue by ok11** [rvera/image-picker#37]
Hi Rodrigo,

first of all many thanks for the great plugin. 
I have some doubt. I understood the documentation in the way that setting hide_select to true must hide only the original select control, leaving the picker visible. When I try to set hide_select to true (or just omit it in the imagepicker call, because it is by default set to true), actually both disappear: the select control and the picker. I assume it is not by design, or?
I tested with jquery 1.11 and Chrome.

**Comment by nickanon** [comment]
Was this ever resolved?  I'm trying to use the image picker and no matter what settings I try I cannot set hide-select: true  to work.  I've tried setting hide_select : true in my jquery initialize but doesn't make a difference.  The only time it hides is when I set up the image picker using multiple="multiple" but I don't want to allow multiple.  Thanks for any feedback.

**Comment by rvera** [comment]
Weird, I tested the demo page and ran this in the javascript console ` $("select").imagepicker({hide_select: true})` and it did hide all of them. It does this by putting an     `display: none` rule in the element but if you have another css rule with `!important` it might be overriding that.

**Comment by nickanon** [comment]
Thanks for the tip.  Will try out tomorrow.


Date: Wed, 30 Mar 2016 18:12:26 -0700
