### ISSUE TITLE
Rebinding causes issue with Knockout

### ISSUE THREAD

**Issue by ewassef** [rvera/image-picker#49]
When calling .imagepicker on a select box that is bound to knockout the first time everything works fine. When that select list is changed and the call is made again (as is recommended) the underlying select list seems to never receive the updates on when an item is selected. the thumbnail does highlight correctly though. 

Is there a way to totally destroy the first instance and recreate it? the destroy method seems to leave some stuff behind. 

Knockout is mentioned because it is more apparent with knockout. The scenario is items get added to the list from other dom events and would be added or removed from the master select list. The user would then get the option to pick from this master list. Things work great on the first time around but stop once anything is changed on the select list

**Comment by ewassef** [comment]
ImagePicker.prototype.destroy = function () {
            var option, _i, _len, _ref;
            _ref = this.picker_options;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                option = _ref[_i];
                option.destroy();
            }
            this.picker.remove();
            //this.select.unbind("change"); //Removing this line resolves the issue
            this.select.removeData("picker");
            return this.select.show();
        };

**Comment by rvera** [comment]
Thanks for this @ewassed, can you provide a jsfiddle example with the issue?

You are probably not the only one seeing this and would love to fix it.

**Comment by rvera** [comment]
Thanks for reporting this, came back to it a year later. 

It's obvious to me now what was probably the issue `this.select.unbind("change")` was probably removing all listeners and instead of only the ones I added. Made a fix for this in the latest release.
