### ISSUE TITLE
Selected Option

### ISSUE THREAD

**Issue by diogogomeswww** [rvera/image-picker#54]
I've set a selected option
<code>option value="xpto" selected</code>
on the original html select element.

But the generated div with the images ignores that selection.

Am I doing something wrong? or this plugin doesn't do this?

Thanks

**Comment by rvera** [comment]
Hi there, do you set that on the HTML or through javascript?

**Comment by diogogomeswww** [comment]
Hi,

I'm really sorry, I've should had close this ticket.
It was a bug on my part.

Thanks for answering!
Cheers

**Comment by rvera** [comment]
Thanks @diogogomeswww and sorry for the late reply.
