### ISSUE TITLE
Making thumbnails responsive

### ISSUE THREAD

**Issue by dcanora** [rvera/image-picker#56]
Great plugin!  I'm wondering - is there a way to make the thumbnails responsive so they play nicely on mobile devices?  Thanks!

David.

**Comment by pingtux** [comment]
I had to make the thumbnails responsive for a project I'm working on. My solution was to add `width: 50%` to `ul.thumbnails.image_picker_selector li`. Now they scale nicely on mobile devices.

Depending on your needs, you can play around with this value.

**Comment by dcanora** [comment]
Thanks for your reply. I'll give it a shot.

**Comment by rvera** [comment]
@pingtux proposals is the preferred one, this is up to each app and should be solved at the CSS layer.
