### ISSUE TITLE
Add the source to CDNJS

### ISSUE THREAD

**Issue by hajekj** [rvera/image-picker#57]
It would be great if you could add this project to [cdnjs](http://cdnjs.com) so it could be loaded from a CDN without having to include the source in my project.

**Comment by bbashy** [comment]
@hajekj Can do it yourself within the cdnjs site

**Comment by hajekj** [comment]
Right, created https://github.com/cdnjs/cdnjs/issues/6475 for it to be included.

**Comment by rvera** [comment]
Thanks for doing this
