### ISSUE TITLE
Pagination of images

### ISSUE THREAD

**Issue by iohannis** [rvera/image-picker#58]
Is it possible to paginate the results? - Say that the select box has 1000 items in it, how would I paginate the thumbnails to only show a subset (50, for instance) at a time?

**Comment by privettoli** [comment]
Looks like there is no pagination.
@iohannis, what did you choose in your case?

**Comment by rvera** [comment]
This is supposed to replace a simple short `SELECT` element. If there was pagination this would lead to some weird UX cases, like selecting multiple elements on different pages but not being able to see all the selected ones at once. 

Sadly it's outside of the scope for now but feel free to extend it.

**Comment by privettoli** [comment]
@rvera, a real case scenario: lazy loading of images.
