### ISSUE TITLE
image picker not working on 2nd page`

### ISSUE THREAD

**Issue by etype** [rvera/image-picker#63]
good day 

thanks for your script it is very cool
but now i have this problem i have some files called 
head.php - where i keep all the css files and scripts
getpic.php - works nicely i can choose and submit 
meds.php - dont know why not working
process_selected_mood_message.php - send to screen works perfectly
process_selected_meds.php - not working single select not optgroup

i have put all the code for the 5 files and there processor files please can you tell me why the getpic.php file is working perfectly , but the meds.php file has no <optgroup> and does not want to work ?
please help me

i will now paste each files code here
head.php
-------------
  <head>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="HandheldFriendly" content="true">
    <title>Corcoora</title>
    
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<link href="bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
	<link href="bootstrap/css/image-picker.css" rel="stylesheet">
	<link href="bootstrap/css/styles.css" type="text/css" rel="stylesheet">
	<link href="bootstrap/css/dropzone.css" type="text/css" rel="stylesheet" />

  </head>

    <script src="bootstrap/jquery/jquery.min.js"></script>
    
    <script src="bootstrap/js/bootstrap.min.js"></script>
	<script src="bootstrap/js/image-picker.js"></script>
	<script src="bootstrap/js/dropzone.min.js"></script>
	<script src="bootstrap/js/panelscript.js"></script>
---------
getpic.php
---------
<!DOCTYPE html>
<html lang="en">
<?php include 'head.php';?>
<?php include 'mm.php';?>
  <body>
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="picker">
						<?php
							$myDirectory = opendir("pics/mood/");
							while($entryName = readdir($myDirectory)) {
							$dirArray[] = $entryName;
							}
							closedir($myDirectory);
							$indexCount	= count($dirArray);
						?>
						<br>
				<select class="image-picker show-html" data-limit="2" multiple="multiple">
					<optgroup label="Mood - Select First Picture, will show for 7 seconds">
						<?php
							for($index=0; $index < $indexCount; $index++) {
							$extension = substr($dirArray[$index], -3);
							if ($extension == 'jpg'){ 
						?>
						<?php
							echo '<option data-img-src="pics/mood/' . $dirArray[$index] . '" value="' . $dirArray[$index] . '" type="mood" />' . $dirArray[$index] . '</option>';
						?>
						<?php
							}	
						}
						?>
			        </optgroup>
						<?php
							$myDirectory1 = opendir("pics/jpg/");
							while($entryName1 = readdir($myDirectory1)) {
							$dirArray1[] = $entryName1;
							}
							closedir($myDirectory1);
							$indexCount	= count($dirArray1);
						?>
						<br>
						<optgroup label="Mood - Choose Second Picture will stay on screen till you close">
					    <?php
							for($index=0; $index < $indexCount; $index++) {
							$extension = substr($dirArray1[$index], -3);
							if ($extension == 'jpg'){ // list only jpgs
						?>
						<?php
							echo '<option data-img-src="pics/jpg/' . $dirArray1[$index] . '" value="' . $dirArray1[$index] . '" type="mood" />' . $dirArray1[$index] . '</option>';
						?>
						<?php
							}	
						}
						?>
			             </optgroup>
				</select>	
<input class="btn btn-default" type="button" value="Send to Corcoora" onclick="moodsubmit();">
<script ="text/javascript">
$(document).ready(function () {
    $(".image-picker").imagepicker({
    hide_select:  true,
	show_label: false,
    });
});
function moodsubmit(){

    var selectedMediaItems = new Array();
    var mediaType = "image";
    $("select.image-picker option:selected").each(function(){
    	selectedMediaItems.push($(this).val());
		mediaType = $(this).attr("type")
	});

    if (mediaType == "mood") {
		$.post("menu/process_selected_mood_message.php", { moods: selectedMediaItems } )
		.done(function(data) {
	    	// alert( "Data Loaded: " + data );
	  	});
    } else if (mediaType == "video") {
		$.post("menu/process_selected_videos.php", { videos: selectedMediaItems } )
		.done(function(data) {
	    	// alert( "Data Loaded: " + data );
	  	});
    }
  	
}
</script>

				</div>

			</div>
		</div>
	</div>
	</body>
</html>
----------
meds.php
----------
<!DOCTYPE html>
<html lang="en">
<?php include 'head.php';?>
<?php include 'mm.php';?>
  <body>
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="picker">
						<?php
							$myDirectory = opendir("pics/med/");
							while($entryName = readdir($myDirectory)) {
							$dirArray[] = $entryName;
							}
							closedir($myDirectory);
							$indexCount	= count($dirArray);
						?>
						<br>
				<select class="image-picker show-html" data-limit="1">
						<?php
							for($index=0; $index < $indexCount; $index++) {
							$extension = substr($dirArray[$index], -3);
							if ($extension == 'jpg'){ 
						?>
						<?php
							echo '<option data-img-src="pics/med/' . $dirArray[$index] . '" value="' . $dirArray[$index] . '" type="meds" />' . $dirArray[$index] . '</option>';
						?>
						<?php
							}	
						}
						?>
				</select>	
<input class="btn btn-default" type="button" value="Send to Corcoora" onclick="medsubmit();">
<script ="text/javascript">
$(document).ready(function () {
    $(".image-picker").imagepicker({
    hide_select:  true,
	show_label: false,
    });
});
function medsubmit(){

    var selectedMediaItems = new Array();
    var mediaType = "image";
    $("select.image-picker option:selected").each(function(){
    	selectedMediaItems.push($(this).val());
		mediaType = $(this).attr("type")
	});

    if (mediaType == "meds") {
		$.post("menu/process_selected_meds.php", { medss: selectedMediaItems } )
		.done(function(data) {
	    	// alert( "Data Loaded: " + data );
	  	});
    } else if (mediaType == "video") {
		$.post("menu/process_selected_videos.php", { videos: selectedMediaItems } )
		.done(function(data) {
	    	// alert( "Data Loaded: " + data );
	  	});
    }
  	
}
</script>

				</div>

			</div>
		</div>
	</div>
	</body>
</html>
----------
process_selected_mood_message.php - works fine with optgroup
----------
<?php
$moods = $_POST["moods"];
// $result = count($moods);
echo exec('sudo -u pi kill $(pgrep mirage) ; export DISPLAY=\':0\' ; export XAUTHORITY=/home/pi/.Xauthority ; sudo -u pi mirage -f /var/www/corcoora/pics/mood/' . $moods[0] . ' & sleep 7 ; sudo -u pi mirage -f /var/www/corcoora/pics/jpg/' . $moods[1] . '');
?>
-------
process_selected_meds.php not sure if its this file or meds.php with problem
--------
<?php
$medss = $_POST["medss"];
// $result = count($medss);
echo exec('sudo -u pi fbi -noverbose -T 1 -a -u -t 1 /var/www/corcoora/pics/med/' . $medss[0]);
?>
---------

thank you if anyone can help me

**Comment by etype** [comment]
why is it cutting out my code what must i do

**Comment by bbashy** [comment]
@etype Use code blocks...

**Comment by rvera** [comment]
Difficult to test without the code, I assume you change the DOM so you need to re init the plugin.
