### ISSUE TITLE
Select HTML is not showing

### ISSUE THREAD

**Issue by atmalatif** [rvera/image-picker#65]
I have a problem with code. How to show select html after use select to imagepicker.
Example:
$(function(){
  	$("select").imagepicker();
  });
And it works to show image picker. But when I try to show select HTML function, it's not showing anything. Just show select style="display:none"?? How i fix it?

**Comment by rvera** [comment]
Seems like you found a solution for this, great!

**Comment by atmalatif** [comment]
Yeah, I'm sorry not waiting your reply. I use javascript to showing select.
