### ISSUE TITLE
How to upadte the changed Values in alert

### ISSUE THREAD

**Issue by dkedar** [rvera/image-picker#70]
Hello,
I just gone through this demo you created on jsfiddle: http://jsfiddle.net/Km55L/1/
My question is if I deselect an Image then value of options also changed and in the alert can be display as well. How can I do that?

Regards
Kedar

**Comment by SgtOddball** [comment]
If you look at the jQuery in the jsfiddle, it's got a listener that is looking for the multi select values to be changed and firing an alert box when that happens.
```javascript
//Calls the select box with the class of image-picker and launches imagepicker function
jQuery("select.image-picker").imagepicker({
//Sets the select to display, normally you'd set this to true
  hide_select:  false,
    //this is triggered when an image is selected, passing over the selected option values
    selected: function(option){
        //Gets the values selected from the option that can be called using this.
        var values = this.val();
        //Triggers the alert box with the values selected. 
        alert(values);
    }
});
```

Easy.

**Comment by rvera** [comment]
Thank you @SgtOddball, that looks right/
