### ISSUE TITLE
Jscrollpane for the images

### ISSUE THREAD

**Issue by JohnGrab** [rvera/image-picker#71]
Hey,

first of all thanks for this nice framework.

Is there any possibility to put the images into a jscrollpane?

I need something like shown here (Horizontal only): 
http://jscrollpane.kelvinluck.com/fullpage_scroll.html 

thanks alot.

John

**Comment by rvera** [comment]
I think it's possible, you'll need to integrate jscrollpane with this though, put your code on the `initialized` callback (so the DOM elements are already created) and then execute the `Jscrollpane` code.
