### ISSUE TITLE
Bug with JQuery 3.0.0

### ISSUE THREAD

**Issue by basteos** [rvera/image-picker#78]
Hi, 
I want to inform you that your lib doesn't work with JQuery 3.0.0 :-) We have to work with JQuery 2.2.4

**Comment by UnderlineWords** [comment]
+1

**Comment by rvera** [comment]
Ouch, do you know what changed in JQuery 3? What error are you getting?

**Comment by UnderlineWords** [comment]
Any error message doesn't write to my browser console. But it doesn't work.

Maybe It maybe useful for jQuery changes
https://jquery.com/upgrade-guide/3.0/

**Comment by UnderlineWords** [comment]
Hmm, it works technically when i submit the form but select style doesn't change. So i can't see the my selected items.

**Comment by rvera** [comment]
Interesting, maybe a method got deprecated. I'll take a look later in the week, thanks a lot for the heads up.

**Comment by rdennis** [comment]
The issue seems to be with `both_array_are_equal`. `jQuery::not` is always returning `true`. It seems you just need to replace it with a quick array comparison.

**Comment by gotshoo** [comment]
I replaced

 `
both_array_are_equal = function(a, b) {
    return jQuery(a).not(b).length === 0 && jQuery(b).not(a).length === 0;
};
`
with

`both_array_are_equal = function(a, b) {      
      var difference = [];
      $.grep(a, function (el) {
          if ($.inArray(el, b) == -1) difference.push(el);
      });
      if (difference.length === 0) {
          var $i = 0;
          while ($i < a.length) {
              if (a[$i] !== b[$i]) {
                  return false;
              }
              $i++;
          }
          return true;
      } else {
          return false;
      }
  };`

to get this to work with Jquery 3.0

**Comment by sadgamer** [comment]
hi your code is not working gotshoo

**Comment by rdennis** [comment]
I have a pull request #81 to add jQuery 3 support. Until the request is merged you can use my branch.

**Comment by rvera** [comment]
Excellent work! Merged 🐈
