### ISSUE TITLE
action if mouseover

### ISSUE THREAD

**Issue by manuele89** [rvera/image-picker#83]
Hi,

how can I execute an action when the user move the mouse over the image?

Thank You

Manuele

**Comment by SgtOddball** [comment]
You've got a couple of options but it really depends on just what you're trying to do. You could use CSS hover events or if you're after something else more complex you'd need a javascript/jQuery listener applying after image-picker has drawn the images on screen. 

Can you elaborate as to what you're trying to do?

**Comment by rvera** [comment]
This goes a bit out of scope of the picker.

I think what @SgtOddball recommended is the best option.
