### ISSUE TITLE
data-img-class attribute issue

### ISSUE THREAD

**Issue by ergum** [rvera/image-picker#84]
Hi!

I got crazy finding why data-img-class attribute doesn't work on my project. In my case was because using minified version image-picker.min.js disables this feature. Using the image-picker.js version works perfectly. Using Version 0.3.1

Thanks for the project!

**Comment by ninsky** [comment]
Hi ergum

Thanks for this bug report. Could you give an example how options have to be passed at all? I think the manual lacks this informations.

Thanks in advance
ninsky

**Comment by rvera** [comment]
Thanks @ergum and @ninsky, will take a look.

**Comment by mpgn** [comment]
9 month later. Is this project deprecated ?

**Comment by rvera** [comment]
Hey @mpgn I've been struggling a bit to find the time to fix this, if you can make a PR with a fix it would be greatly appreciated.

**Comment by mpgn** [comment]
@rvera I just found after compiling the coffee that the `data-img-class` is working well. The min.js file on the github is not compiled to the lastest coffee script version. THAT the real bug...

Also why apply the class to every element ? 

![!](https://i.gyazo.com/e7a891186bb8946b35fbcfc165230b06.png)

Where the custom class is `col-6`, refering to : 
```coffee
      @node.addClass(imgClass)
      image.addClass(imgClass)
      thumbnail.addClass(imgClass)
``` 
in https://github.com/rvera/image-picker/blob/master/source/coffee/image-picker.coffee#L168

**Comment by Humni** [comment]
@rvera If you accept any of my pull requests this bug will be resolved (and a few others).

**Comment by rvera** [comment]
Closing this since it'll be properly compiled and fixed in the next release.
