### ISSUE TITLE
Image Drag

### ISSUE THREAD

**Issue by 1der1** [rvera/image-picker#85]
I am considering to use the image picker for a page builder. Everything works perfectly.

However, the page builder allows dragging pictures from everywhere, and the thumbnail images in the picker can't be dragged.

It would be fantastic if there would be an option.

**Comment by rvera** [comment]
Hi @1der1, you can add the functionality you need in a callback after the picker has been initialized. Look at the docs here http://rvera.github.io/image-picker/
