### ISSUE TITLE
Ability to delete images

### ISSUE THREAD

**Issue by jonesr91** [rvera/image-picker#95]
Hi there,

Are there any plans to add an option to allow an image to be deleted?
A little cross in the top right corner of the image that appears on hover or something.

Thanks,
Ryan

**Comment by Guite** [comment]
Hover seems not ideal if it should also work on touch devices.

**Comment by jonesr91** [comment]
Good point. Have you got any better solutions?

It would be great to have the option to delete an image by calling an API.

**Comment by rvera** [comment]
No plans for this, the ideas for the plugin is that you provide a set of options and let the users pick from them. Seems like you want the opposite, provide all the options and let the users remove the ones they don't want.

You could cheat around this by creating a picker with all the options selected, when they touch an option it will be unselected. You can hide all unselected options with css.
