### ISSUE TITLE
Re-Loading ImagePicker

### ISSUE THREAD

**Issue by draytop** [rvera/image-picker#96]
Hi,

We are using your image picker and using ajax to load 5 images at a time.
The issue is, if you Add 5 more options to the Select, you have to destroy and then re-initialize the imagepicker. The more images you add, the longer it takes to draw the Select as it has to reload all the images again.

Is there anyway around this?

**Comment by rvera** [comment]
So you don't want to load all the images or all the options at once?

Because you could load all the options, put a placeholder image and then slowly replace all the placeholders with the real images you want.

Otherwise I'd think it falls outside of the scope of the picker.

**Comment by draytop** [comment]
Ok, thankyou for your support.
